Zip each artifact for release.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -78,6 +78,28 @@ jobs:
     steps:
       - name: Download artifacts
         uses: actions/download-artifact@v4
+        with: 
+          path: artifacts
+
+      - name: Zip folders
+        run: |
+          directory=artifacts
+
+          if [ ! -d "$directory" ]; then
+            echo "Error: Directory '$directory' not found."
+            exit 1
+          fi
+
+          for item in "$directory"/*; do
+            if [ -d "$item" ]; then
+              folder_name=$(basename "$item")
+              zip_file="$folder_name.zip"
+              zip -jr "$zip_file" "$item"
+            fi
+          done
 
       - name: Release
         uses: softprops/action-gh-release@v2
+        with:
+          files: |
+            *.zip
